### PR TITLE
handle internal server errors

### PR DESCRIPTION
**Pull request by jsoref**

### CODE REVIEW

**Comment by paskal** [comment]
Could you please provide an example of the error handled with this new exception?

**Comment by jsoref** [comment]
I was querying zabbix for all items, and zabbix ran out of memory.
I've since deleted most of the items (using SQL) and vacuumed the database and increased the apache php memory limit...

The apache2 error log shows something like:
```
[Tue Mar 14 20:52:07.318054 2017] [:error] [pid 30428] [client 10.4.0.100:49590] PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 2 bytes) in /usr/share/zabbix/include/db.inc.php on line 609
```

**Comment by paskal** [comment]
Not Zabbix ran out of memory but apache. I guess it's very easy to reproduce by, could you please post error message before and after your patch with php `memory_limit` set to very low value like 1M?

**Comment by jsoref** [comment]
before:
```py
$ ./zabbix_tool get_graphs
Traceback (most recent call last):
  File "./zabbix_tool", line 933, in <module>
    tool.login(**options)      # Cheating!
  File "./zabbix_tool", line 115, in login
    self.z.login(user=username, password=password)
  File "/Users/jsoref/code/zabbix/scripts/zabbix/build/lib/zabbix_api.py", line 207, in login
    result = self.do_request(obj)
  File "/Users/jsoref/code/zabbix/scripts/zabbix/build/lib/zabbix_api.py", line 261, in do_request
    raise ZabbixAPIException("urllib2.URLError - %s" % e)
zabbix_api.ZabbixAPIException: urllib2.URLError -
```

after:
```py
$ ./zabbix_tool get_graphs
Traceback (most recent call last):
  File "./zabbix_tool", line 933, in <module>
    tool.login(**options)      # Cheating!
  File "./zabbix_tool", line 115, in login
    self.z.login(user=username, password=password)
  File "/Users/jsoref/code/zabbix/scripts/zabbix/build/lib/zabbix_api.py", line 207, in login
    result = self.do_request(obj)
  File "/Users/jsoref/code/zabbix/scripts/zabbix/build/lib/zabbix_api.py", line 261, in do_request
    raise ZabbixAPIException("urllib2.URLError - %s" % e)
zabbix_api.ZabbixAPIException: urllib2.URLError - Internal Server Error
```

**Comment by paskal** [comment]
Thanks a lot! Looks valid to me. @gescheit, could you please review and merge?

**Comment by gescheit** [comment]
Thanks guys!

**Comment by paskal** [comment]
A side-note: I've tested everything, current `master` works as well as 0.3 with Zabbix 3.2, I think you can release new version safely.

**Pull request merged**
